# Generated by Django 4.2.3 on 2023-07-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
